wso2/testgrid-job-configs

- wso2-ei-scenarios-testgrid.yaml
- wso2-is-scenarios-testgrid.yaml
Adds testgrid test config files required to run product scenario tests on TestGrid
> Add testgrid yamls for EI and IS scenarios

- wso2-apim-scenarios-testgrid.yaml
> Add testgrid yamls for apim

- wum-sce-test-wso2is-5.2.0-full-testgrid.yaml
Reverts wso2-incubator/testgrid-job-configs#30
> Revert "Update wum-sce-test-wso2is-5.2.0-full-testgrid.yaml"

- wum-sce-test-wso2ei-6.4.0-full-testgrid.yaml
Remove branch from remoteRepository
> Remove deprecated value

- wum-sce-test-wso2ei-6.4.0-full-testgrid.yaml
> Update InternalPrepareForTest input parameter

- wum-sce-test-wso2ei-6.0.0-full-testgrid.yaml
> Adding InternalPrepareForTest for 6.0.0 test config

- wum-sce-test-wso2ei-6.1.0-full-testgrid.yaml
> Configuring 610 for InternalPrepareForTest

- wum-sce-test-wso2is-5.3.0-full-testgrid.yaml
Move IS-5.3.0 scenario tests to support branch.
> Change 5.3.0 scenario test location to support repository

- wum-sce-test-wso2is-5.2.0-full-testgrid.yaml
move IS-5.2.0 scenario tests to support branch
> Change 5.2.0 scenario test location to support repository

- wum-sce-test-wso2is-5.3.0-full-testgrid.yaml
- wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
prod-wso2is-samples-deployment for is 5.3.0 and introduce product version input parameter.
> Add prod-wso2is-samples-deployment properties for IS-5.3.0

- wum-sce-test-wso2is-5.3.0-full-testgrid.yaml
>update product repository of IS-5.3.0 test config to enable cfn signals to the deployment
> update product repository of IS-5.3.0 test config

- wso2am-intg-testgrid-yaml
- wso2ei-intg-testgrid-yaml
- wso2is-intg-testgrid-yaml
- wso2sp-intg-testgrid-yaml
- wum-sce-test-wso2am-2.1.0-full-testgrid.yaml
- wum-sce-test-wso2am-2.6.0-full-testgrid.yaml
- wum-sce-test-wso2ei-6.0.0-full-testgrid.yaml
- wum-sce-test-wso2ei-6.1.0-full-testgrid.yaml
- wum-sce-test-wso2ei-6.1.1-full-testgrid.yaml
- wum-sce-test-wso2ei-6.4.0-full-testgrid.yaml
- wum-sce-test-wso2esb-4.9.0-full-testgrid.yaml
- wum-sce-test-wso2esb-5.0.0-full-testgrid.yaml
- wum-sce-test-wso2is-5.2.0-full-testgrid.yaml
- wum-sce-test-wso2is-5.3.0-full-testgrid.yaml
- wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
**Purpose**
Update testgrid yaml according to changes in testgrid
**Security checks**
> Change scenario config block

- wso2am-intg-testgrid-yaml
- wso2ei-intg-testgrid-yaml
- wso2is-intg-testgrid-yaml
- wso2sp-intg-testgrid-yaml
- wum-sce-test-wso2am-2.1.0-full-testgrid.yaml
- wum-sce-test-wso2am-2.6.0-full-testgrid.yaml
- wum-sce-test-wso2ei-6.0.0-full-testgrid.yaml
- wum-sce-test-wso2ei-6.1.0-full-testgrid.yaml
- wum-sce-test-wso2ei-6.1.1-full-testgrid.yaml
- wum-sce-test-wso2ei-6.4.0-full-testgrid.yaml
- wum-sce-test-wso2esb-4.9.0-full-testgrid.yaml
- wum-sce-test-wso2esb-5.0.0-full-testgrid.yaml
- wum-sce-test-wso2is-5.2.0-full-testgrid.yaml
- wum-sce-test-wso2is-5.3.0-full-testgrid.yaml
- wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
**Purpose**
Change to ScenarioConfigs
**Security checks**
> Update testgrid yamls

- wso2am-intg-testgrid-yaml
- wso2ei-intg-testgrid-yaml
- wso2is-intg-testgrid-yaml
- wso2sp-intg-testgrid-yaml
- wum-sce-test-wso2am-2.1.0-full-testgrid.yaml
- wum-sce-test-wso2am-2.6.0-full-testgrid.yaml
- wum-sce-test-wso2ei-6.0.0-full-testgrid.yaml
- wum-sce-test-wso2ei-6.1.0-full-testgrid.yaml
- wum-sce-test-wso2ei-6.1.1-full-testgrid.yaml
- wum-sce-test-wso2ei-6.4.0-full-testgrid.yaml
- wum-sce-test-wso2esb-4.9.0-full-testgrid.yaml
- wum-sce-test-wso2esb-5.0.0-full-testgrid.yaml
- wum-sce-test-wso2is-5.2.0-full-testgrid.yaml
- wum-sce-test-wso2is-5.3.0-full-testgrid.yaml
- wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
Add necessary spaces to validate testgrid yamls
> Validate yaml

- wum-sce-test-wso2is-5.2.0-full-testgrid.yaml
- wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
> update IS 5.2.0 and IS 5.7.0 git repository
> update IS 5.2.0 and IS 5.7.0 git repository

- wum-sce-test-wso2is-5.2.0-full-testgrid.yaml
- wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
> Adding few members to the "TO" mailing list of identity server TG builds.
> Adding members to mailing lists

- wum-dev-sce-devtest-wso2am-2.6.0-full-testgrid.yaml
- Add a new config yaml file for wum apim-2.6.0-full for the purpose of developer test requirement for apim.
> Add a new config yaml file for dev test on wum apim-2.6.0-full

- wum-dev-sce-devtest-wso2am-2.6.0-full-testgrid.yaml
- Update apim-dev-test yaml config for pointing dev remote branch.
> Update dev test yaml of apim for new remote branch

- WUM/wum-sce-test-wso2am-2.6.0-full-postgres-testgrid.yaml
- wum-dev-sce-devtest-wso2am-2.6.0-full-testgrid.yaml
> merging kasunbg with devenv

- WUM/wum-sce-test-wso2ei-6.1.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.1.1-full-testgrid.yaml
The purpose of this PR is to update the location of remote repository and relevant script file locations. 
Following product files were updated
* EI - 6.1.0
* EI - 6.1.1
> Update remote repository and script file location for product 6.1.0, 6.1.1

- team-ei/dev-wum-sce-test-wso2ei-6.0.0-full.yaml
- team-ei/dev-wum-sce-test-wso2ei-6.1.0-full.yaml
- team-ei/dev-wum-sce-test-wso2ei-6.1.1-full.yaml
- team-ei/dev-wum-sce-test-wso2ei-6.4.0-full.yaml
- team-ei/dev-wum-sce-test-wso2esb-4.9.0-full.yaml
- team-ei/dev-wum-sce-test-wso2esb-5.0.0-full.yaml
> Update yaml files

- wum-dev-sce-devtest-wso2am-2.6.0-full-testgrid.yaml
Update deployment pattern name to "two-node-deployment"
> Update deployment pattern name

- team-ei/milinda-dev-wum-sce-test-wso2ei-6.1.1-full.yaml
> Add ei 611 testgrid job for milinda
> Add ei 611 testgrid job for milinda

- WUM/wum-sce-test-wso2ei-6.0.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.1.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.1.1-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.4.0-full-testgrid.yaml
The purpose of this PR is to add product version to populate properties file.
Add product version "6.4.0", "6.1.1", "6.1.0", "6.0.0"
> Add product version in EI yaml files

- WUM/wum-sce-test-wso2is-5.2.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.3.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
> Adding new TG build email recipients and removed few existing recipients who are no longer working on scenario automation.
> Modify Recipient List

- WUM/wum-sce-test-wso2ei-6.0.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.1.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.1.1-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.4.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2esb-4.9.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2esb-5.0.0-full-testgrid.yaml
The purpose of this PR is to update the product version in EI job configs
Add product version "EI-6.4.0", "EI-6.1.1", "EI-6.1.0", "EI-6.0.0", "ESB-4.9.0", "ESB-5.0.0"
> Update Product Version in yaml files

- WUM/wum-sce-test-wso2ei-6.0.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.1.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.1.1-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.4.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2esb-4.9.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2esb-5.0.0-full-testgrid.yaml
The purpose of this PR is to update emailToList in EI and ESB configuration files
> Update emailToList in EI/ESB configuration files

- infra-test/wum-sce-test-wso2am-2.6.0-oracle-testgrid.yaml
> Add a build for APIM 2.6.0 with oracle DB
> Testing APIM 2.6.0 with Oracle DB
> Add a build for APIM 2.6.0 with oracle DB

- team-apim/achini-wso2am-2.6.0-full.yaml
Add achini-wso2am-2.6.0-full.yaml file to generate Jenkins job for testing purpose
> add achini-wso2am-2.6.0-full.yaml file to apim

- WUM/wum-sce-test-wso2esb-4.9.0-full-testgrid.yaml
The purpose of this PR is to update configuration file in ESB-4.9.0
Add MySQL-5.6
> Update esb-4.9.0 yaml file

- infra-test/wum-sce-test-wso2ei-6.1.0-full-testgrid.yaml
- infra-test/wum-sce-test-wso2ei-6.1.1-full-testgrid.yaml
- infra-test/wum-sce-test-wso2ei-6.4.0-full-testgrid.yaml
> Run wso2ei scenario tests with regards to given product versions.
> Fix issue with scenario test for wso2ei and introduce a new parameter for product version.
> Introduce new parameter for product version in wso2ei scenario tests.
> Add product version parameter for wso2ei scenario tests

- infra-test/wum-sce-test-wso2esb-4.9.0-full-testgrid.yaml
- infra-test/wum-sce-test-wso2esb-5.0.0-full-testgrid.yaml
> Run wso2ei scenario tests with regards to given product versions.
> Fix issue with scenario test for wso2ei and introduce a new parameter for product version.
> Introduce new parameter for product version in wso2ei scenario tests.
>  Add product version parameter for wso2esb scenario tests

- infra-test/wum-sce-test-wso2am-2.1.0-full-testgrid.yaml
- infra-test/wum-sce-test-wso2am-2.6.0-full-testgrid.yaml
> Change test repository branch name.
> Use APIM scenario tests for test grid builds.
> Change test repository branch name in the configuration yaml.
> Change APIM scenario test repository branch

- team-iam/ayesha-wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
Test build for the testing purpose.
> Add dev build for 5.7.0

- team-iam/ayesha-wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
>  Point to dev test scenarios

- team-ei/milinda-dev-wum-sce-test-wso2ei-6.4.0-full.yaml
> Add dev EI 640 build job for milinda
> Add dev EI 640 build job for milinda

- team-iam/thanuja-wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
> Add thanuja-wum-sce-test-wso2is-5.7.0-full-testgrid.yaml …
> Add thanuja-wum-sce-test-wso2is-5.7.0-full-testgrid.yaml

- infra-test/wum-sce-test-wso2am-2.2.0-full-testgrid.yaml
- infra-test/wum-sce-test-wso2am-2.5.0-full-testgrid.yaml
> Add Testgrid jobs for APIM 2.5.0 and 2.2.0
> Add APIM 2.2.0 and 2.5.0

- team-ei/dev-wum-sce-test-wso2ei-6.2.0-full.yaml
The purpose of this PR is to add yaml file for product version EI-6.20
Add dev-wum-sce-test-wso2ei-6.2.0-full.yaml
> Add configuration file for product version EI-6.2.0

- team-ei/dilmi-dev-wum-sce-test-wso2ei-6.4.0-full.yaml
The purpose of the PR is to add dilmi-dev-wum-sce-test-wso2ei-6.4.0-full.yaml file for testing purpose
> Add configuration file

- team-ei/dev-wum-sce-test-wso2ei-6.3.0-full.yaml
The purpose of this PR is to add configuration file for EI - 6.3.0
> Add configuration file for product verison - EI-6.3.0

- infra-test/wum-sce-test-wso2am-2.2.0-full-testgrid.yaml
- wum-dev-sce-devtest-wso2am-2.6.0-full-testgrid.yaml
> Add new email subscriber for APIM builds
> Update APIM email subscribers

- WUM/wum-sce-test-wso2ei-6.2.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.3.0-full-testgrid.yaml
The purpose of this PR is to add EI-6.2.0 & EI-6.3.0 configuration files.
> Add configuration files for EI-6.2.0 & EI-6.3.0

- team-iam/piraveena-wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
> Adding testgrid yaml file

- team-iam/sarubi-wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
> Add sarubi-wum-sce-test-wso2is-5.7.0-full-testgrid.yaml. …
> Add sarubi-wum-sce-test-wso2is-5.7.0-full-testgrid.yaml

- WUM/wum-sce-test-wso2is-5.2.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.3.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
> Add RemoteProductDir input parameter for is 5.7.0, 5.3.0 and 5.2.0

- WUM/wum-sce-test-wso2ei-6.1.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.1.1-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.2.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.3.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.4.0-full-testgrid.yaml
> Add RemoteProductDir input param to ei 6.1.0 - 6.4.0

- WUM/wum-sce-test-wso2esb-4.9.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2esb-5.0.0-full-testgrid.yaml
> Add RemoteProductDir input param to esb 5.0.0 - 4.9.0

- WUM/wum-sce-test-wso2is-5.2.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.3.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
> Add new members to the email list.
> Modify emailToList for IS 5.2.0, 5.3.0 and 5.7.0

- team-iam/thushanthan-wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
> Add thushanthan-wum-sce-test-wso2is-5.7.0-full-testgrid.yaml. …
> Add thushanthan-wum-sce-test-wso2is-5.7.0-full-testgrid.yaml

- WUM/wum-sce-test-wso2ei-6.4.0-full-testgrid.yaml
The purpose of this PR is to add ActiveMQ and VFS backends to EI yaml files and update emailTo list in EI-6.4.0.
> Add ActiveMQ and VFS backends

- WUM/wum-sce-test-wso2ei-6.4.0-full-testgrid.yaml
> Fix formatting

- WUM/wum-sce-test-wso2am-2.6.0-full-testgrid.yaml
Update email notifier list for prod jobs
> Update email notifier list

- team-apim/praminda-wso2am-2.6.0-full.yaml
Add personal dev build for debugging purposes
> Add personal dev build

- team-ei/ridmi-correto-jdk-wso2ei-6.4.0-full.yaml
This PR includes the job config for test compatibility of corretto jdk with scenario tests. 
Running scenario tests for combination of
OS - CentOS, Ubuntu
DK - Corretto JDK
DB - MySQL
> Link to the PR for changes to the training …
> Add testgrid job config for EI 6.4.0 to support corretto jdk

- team-iam/thanuja-wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
> Updating to CorrettoJDK-8
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
> Updating to CorrettoJDK-8

- team-iam/thanuja-wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
> Change OS to CentOS-7.5 for the dev build. …
> Change OS to CentOS-7.5 for the dev build.

- team-ballerina/bbg-data.yaml
> Add bbg-data yaml

- Ballerina/bbg-data.yaml
> Add data BBG yaml

- team-ballerina/bbg-data.yaml
> Update dev branch for bbg-data.yaml

- team-ballerina/bbg-http.yaml
> Add testgrid yaml for Ballerina HTTP BBGs

- team-ballerina/bbg-data-new-repo.yaml
> Add yaml for new repo test

- Ballerina/bbg-data.yaml
> Update yaml of the bbg-data job

- team-ballerina/bbg-kafka.yaml
> Add Kafka BBG to test jobs

- RELEASES/sce-test-wso2is-testgrid.yaml
> Add sce-test-wso2is-testgrid.yaml …
> Add sce-test-wso2is-testgrid.yaml

- team-ballerina/bbg-data-new-repo.yaml
> Update dev job yaml

- wso2is-intg-testgrid-yaml
Change test running file name to test.sh
> change test running file to test.sh

- wso2is-intg-testgrid-yaml
Change test running file to test.sh
> Change test running file

- infra-test/wum-sce-test-wso2am-2.6.0-full-testgrid-SUSE.yaml
- infra-test/wum-sce-test-wso2ei-6.4.0-full-testgrid-SUSE.yaml
- infra-test/wum-sce-test-wso2is-5.7.0-full-testgrid-SUSE.yaml
> Add new testing environments. ( SUSE Linux 12 and Postgres 9.4.12)
> Run the tests on SUSE Linux 12 and Postgres 9.4.12 for test compatibility of the WSO2 Products.
> Add configurations for SUSE Linux 12 and Postgres 9.4.12.
> Add tests for SUSE-Linux-12 and Postgres-9.4.12

- infra-test/wum-sce-test-wso2ei-6.4.0-full-testgrid-SUSE.yaml
- infra-test/wum-sce-test-wso2is-5.7.0-full-testgrid-SUSE.yaml
> Change elastic search endpoint URL with a new elastic search URL
> Store elastic search logs. 
> Replace elastic search endpoint URL from a new URL.
> Change elastic search endpoint url

- infra-test/wum-sce-test-wso2ei-6.4.0-full-testgrid-SUSE.yaml
- infra-test/wum-sce-test-wso2is-5.7.0-full-testgrid-SUSE.yaml
> Chnage configuration in SUSE Linux tests. 
> Change the test repositories and other configuration that related to the SUSE Linux configurations.
> Update configurations in SUSE Linux tests

- infra-test/wum-sce-test-wso2am-2.6.0-full-testgrid-SUSE.yaml
- infra-test/wum-sce-test-wso2ei-6.4.0-full-testgrid-SUSE.yaml
- infra-test/wum-sce-test-wso2is-5.7.0-full-testgrid-SUSE.yaml
> Change OS of test configurations in IS-5.7.0 and EI-6.4.0.
> Test IS-5.7.0 and EI-6.4.0 against CentOS 7.
> Change OS of test configurations in IS-5.7.0 and EI-6.4.0.

- infra-test/wum-sce-test-wso2am-2.6.0-full-testgrid-SUSE.yaml
> Change APIM configurations in SUSE-Linux tests
> Pointing to a new repository for testing.
> Change APIM configurations in SUSE-Linux tests

- wso2ei-intg-testgrid-yaml
> Change the test mode config parameter in wso2ei-intg-testgrid-yaml.
> Change test mode in wso2ei-intg-testgrid-yaml

- achini-wso2is-intg-testgrid-yaml
Create a new yaml file for IS integration test
> add yaml file for IS integration test

- wso2is-intg-testgrid-yaml
Modified Email list and remote repository
> modified email list and remote repository

- RELEASES/sce-test-wso2is-testgrid.yaml
> Update is-samples location.

- RELEASES/sce-test-wso2ei-testgrid.yaml
> This file contains config details for running wso2 ei scenario tests for the latest release.
> Add sce-test-wso2ei-testgrid.yaml

- achini-wso2is-intg-testgrid-yaml
> Change OS type

- team-ballerina/bbg-kafka-new.yaml
> Add new BBG Kafka test job

- team-ballerina/bbg-kafka-new.yaml
> Add remote branch configuration file

- RELEASES/sce-test-wso2is-testgrid.yaml
> Update product location to alpha 2 release. …
> Update product location to alpha 2 release.

- team-ballerina/bbg-integration-patterns.yaml
> Add testgrid job for bbg-integration-patterns

- piraveena-wso2is-intg-testgrid-yaml
> Adding yaml file for IS integration tests

- piraveena-wso2is-intg-testgrid-yaml
> Changing to CentOS

- piraveena-wso2is-intg-testgrid-yaml
> Changing to centOS7.5

- piraveena-wso2is-intg-testgrid-yaml
> Changing instance type

- piraveena-wso2is-intg-testgrid-yaml
> Changing db as MySQL

- piraveena-wso2is-intg-testgrid-yaml
> Changing to windows

- team-ob/wum-dev-sce-wso2ob-1.3.0-full-testgrid.yaml
Add OB 1.3.0 scenario test job
> Add OB 1.3.0 scenario test job

- RELEASES/intg-test-wso2ei-master-testgrid.yaml
Add more infra combination for includes section to verify that the integration tests are successfully running on given infra combinations.
https://github.com/wso2/product-ei/issues/3433
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
> Add more infra combination to includes section

- RELEASES/intg-test-wso2is-master-testgrid.yaml
> Adding yaml file to live env

- RELEASES/intg-test-wso2ei-master-testgrid.yaml
> Change infra combination to test CorrettoJDK

- Ballerina/bbg-integration-patterns.yaml
> Add integration-patterns job

- piraveena-wso2is-intg-testgrid-yaml
> Changing to forked testgrid repo

- piraveena-wso2is-intg-testgrid-yaml
> Changing to forked repo

- wso2is-intg-testgrid-yaml
> Increasing instance type on live environment

- RELEASES/intg-test-wso2is-master-testgrid.yaml
> Test with windows in live environment

- RELEASES/intg-test-wso2is-master-testgrid.yaml
> Adding all DBs

- RELEASES/intg-test-wso2is-master-testgrid.yaml
> Removing OpenJDK8

- RELEASES/intg-test-wso2is-master-testgrid.yaml
> Removing Postgress

- RELEASES/intg-test-wso2ei-master-testgrid.yaml
> Change infra combination to test windows with Adopt and corretto JDK

- piraveena-wso2is-intg-testgrid-yaml
> Changing to forked product-is repo

- piraveena-wso2is-intg-testgrid-yaml
> Changing to wso2 product-is repo

- dev-piraveena-wso2is-intg-testgrid-full.yaml
> Adding testgridYamlUrl to point to own yaml file

- RELEASES/intg-test-wso2ei-master-testgrid.yaml
> Change infrastructure  combination to run Centos

- RELEASES/intg-test-wso2is-master-testgrid.yaml
> Adding all infras to live environment

- RELEASES/intg-test-wso2ei-master-testgrid.yaml
> Change infrastructure combination to test CentOS and Windows

- RELEASES/intg-test-wso2is-master-testgrid.yaml
> Testing on previously working infras for IS

- RELEASES/intg-test-wso2ei-master-testgrid.yaml
Change the job config file to test infrastructure combination for Ubuntu. 
includes:
- Ubuntu-18.04
- MySQL-5.7
- CorrettoJDK-8
- OracleJDK-8
https://github.com/wso2/product-ei/issues/3433
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
> Change infrastructure combination to test Ubuntu

- dev-piraveena-wso2is-intg-testgrid-rhel.yaml
> Adding yaml to  with rhel os in dev

- RELEASES/intg-test-wso2is-master-testgrid.yaml
> Testing correttojdk in live env

- RELEASES/intg-test-wso2is-master-testgrid-centos.yaml
- RELEASES/intg-test-wso2is-master-testgrid-rhel.yaml
- RELEASES/intg-test-wso2is-master-testgrid-ubuntu.yaml
- RELEASES/intg-test-wso2is-master-testgrid-windows.yaml
> Adding different jobs for each OS combinations

- RELEASES/intg-test-wso2ei-master-testgrid-centos.yaml
- RELEASES/intg-test-wso2ei-master-testgrid-rhel.yaml
- RELEASES/intg-test-wso2ei-master-testgrid-ubuntu.yaml
- RELEASES/intg-test-wso2ei-master-testgrid-windows.yaml
This PR includes the separate yaml files for each OS.
OS's are - Centos, Windows, Ubuntu, Redhat
https://github.com/wso2/product-ei/issues/3433
> Link to the PR for changes to the …
> Add separate job config yaml files for EI integration

- team-ballerina/soap.yaml
> Add configuration file for soap scenario test

- team-ei/wso2ei-intg-testgrid-6.5.0-CentOS.yaml
This PR is for running integration test for the product-ei 6.5.0 on CentOS.
> Add yaml file path

- team-ei/kasuna-intg-test-wso2ei-master-testgrid-windows-yamlpath.yaml
> This PR is for running integration test for the product-ei 6.5.0 on Windows.
> Add yaml file path for windows

- team-ob/pasindu-dev-sce-wso2ob-1.3.0-full-testgrid.yaml
- team-ob/wum-dev-sce-wso2ob-1.3.0-full-testgrid.yaml
Add OB testgrid job with CloudFormation
> Add OB testgrid job with CloudFormation

- team-ei/kasuna-scenario-test-wso2ei-6.5.0-testgrid-CentOS-yamlpath.yaml
> This PR is for running scenario tests for the product-ei 6.5.0.
> Add yaml file for scenario test

- Ballerina/soap.yaml
> Add config file for soap scenario test

- WUM/wum-sce-test-wso2esb-5.0.0-full-testgrid.yaml
> This PR is for comment out SUSE-Linux-12 in from the wum-sce-test-wso2esb-5.0.0-full-testgrid.yaml file.
> Comment out SUSE-Linux-12

- team-ballerina/soap.yaml
> Add soap test config file for dev env

- RELEASES/sce-test-wso2ei-testgrid.yaml
> This PR is updated the notification list and jdk version in sce-test-wso2ei-testgrid.yaml file.
> Add OPEN_JDK8 to yaml file

- RELEASES/sce-test-wso2ei-testgrid.yaml
> This PR is for update the ProductLocation release tag in sce-test-wso2ei-testgrid.yaml file.
> Update ProductLocation tag

- RELEASES/sce-test-wso2ei-testgrid_ubuntu.yaml
> This PR is for add sce-test-wso2ei-testgrid_ubuntu.yaml.
> Add sce-test-wso2ei-testgrid_ubuntu.yaml

- RELEASES/sce-test-wso2ei-testgrid.yaml
> This PR is for Update ProductLocation tag for rc1.
> Update ProductLocation tag for rc1

- RELEASES/sce-test-wso2ei-testgrid.yaml
>This PR for update the sce-test-wso2ei-testgrid.yaml.
> Comment out ubuntu

- RELEASES/sce-test-wso2ei-testgrid.yaml
> This PR for update the yaml.
> Add yaml file

- Ballerina/soap.yaml
- RELEASES/sce-test-wso2is-testgrid.yaml
Added oracle and sql support for the sce-test-wso2is-testgrid.yaml
>  Update sce-test-wso2is-testgrid.yaml with oracle and sql

- RELEASES/sce-test-wso2ei-testgrid_SUSE-Linux-12.yaml
> This PR is for add add yaml file fro SUSE-Linux-12.
> Add yaml file fro SUSE linux

- RELEASES/sce-test-wso2is-testgrid.yaml
Update sce-test-wso2is-testgrid.yaml for redhat
> Update sce-test-wso2is-testgrid.yaml for redhat

- RELEASES/intg-test-wso2ei-master-testgrid-centos.yaml
> This PR is for update the notification list.
> Update notification list

- RELEASES/sce-test-wso2ei-testgrid-centos.yaml
> This PR is for update the includes in yaml file and ymal file name.
> Update yaml includes

- RELEASES/sce-test-wso2ei-testgrid_ubuntu.yaml
> This PR is for update the yaml file.
> Update yaml file

- RELEASES/sce-test-wso2ei-testgrid.yaml
> This PR is for update yaml file.
> Update yaml file includes

- team-tg/testgrid_am.yaml
> kubernetes-provision-1.0

- team-tg/testgrid_am.yaml
> add-includes

- team-ballerina/bbg-data-new-repo.yaml
> Add the updated yaml

- RELEASES/intg-test-wso2ei-master-testgrid-centos.yaml
> This PR for change the test mode.
> Change test mode

- team-tg/testgrid_am.yaml
> modify-scripts-location

- RELEASES/intg-test-wso2ei-master-testgrid-windows.yaml
> This PR for update TEST_MODE as RELEASE.
> Update test mode

- RELEASES/sce-test-wso2ei-testgrid-centos.yaml
>This PR is for update the yaml file includes.
> Add includes to the yaml

- RELEASES/sce-test-wso2ei-testgrid-centos.yaml
> This PR for update comment out the mysql-5.7.
> Comment out mysql-5.7

- team-ballerina/artemis-connector.yaml
> Add testgrid yaml for the Artemis connector tests
> Added a dev test job
> Add testgrid yaml for the Artemis connector tests

- team-ballerina/rabbitmq-connector.yaml
> Add testgrid yaml for the RabbitMQ connector tests
> Add testgrid yaml for the RabbitMQ connector tests

- team-ob/wum-dev-sce-wso2ob-1.3.0-full-testgrid.yaml
> Add customized job config yaml
> Add customized job config yaml

- ballerina_integrator_tests.yaml
This PR includes ballerina_integrator_tests.yaml.
> Add ballerina_integrator_tests.yaml

- team-tg/kosala-tg-cost-optimization-tester.yaml
> Add initial job configurations with cost optimizing scheduling. This new structure of the job configurations will enable the scheduled tasks and it will help to optimize cost.
> New job configuration contain new structure to describe the scheduled builds and this builds can be categorized depend on the triggering time. (ex: daily, weekly, monthly)
> Modify cost optimize testing job config file

- team-tg/ranika-am210-test.yaml
> Add testgrid.yaml to test boolean & url issue fix

- team-tg/wum-sce-test-k8s-wso2am-dist.yaml
- team-tg/wum-sce-test-k8s-wso2ei.yaml
test the testgrid distribution with the new modifications added for kubernetes deployments.
> add new testplan with new changes in the distribution

- Ballerina/artemis-connector-scenario-tests.yaml
> Create a new job in test grid prod to run Artemis connector scenario tests
> The complete scenario is from https://github.com/ballerina-platform/ballerina-scenario-tests/pull/29
> Add testgrid yaml for the Artemis connector scenario tests

- team-tg/kosala-tg-cost-optimization-tester.yaml
> Update testgrid yaml file to add includes section for minimize generating test plans.
> Add parameters for includes section in infrastructure configurations.
> Add include section

- team-tg/ranika-am210-test.yaml
> Change infra, dep and test repos

- janeth-aws-apim-test.yaml
> Created a new yaml file to test aws-apim
> Add config file to test apim

- team-tg/wum-sce-test-helm-wso2am.yaml
Test deployment of k8s files through helm charts
> add helm test job

- team-tg/wum-sce-test-k8s-wso2is.yaml
Test k8s deployment for the wso2 is product
> add test wso2 is test for k8s

- team-tg/ranika-testgrid-3.yaml
Add test to test new distribution of reduced sized
> Add New test for testing reduced sized Deployment

- team-tg/kasunA-ballerina-integrator-k8s.yaml
> This PR includes ballerina-integrator-k8s.yaml.
> Add ballerina-integrator-k8s.yaml

- WUM/wum-sce-test-wso2is-5.8.0-full-testgrid.yaml
Add job configs to run scenario tests against IS 5.8.0
> Add job config for wum sceanrio tests against IS 5.8.0

- team-tg/wum-sce-test-helm-wso2am.yaml
> Update jenkins job wum-sce-test-helm-wso2am
>  Add infrastructure changes and change remoteRepository

- WUM/wum-sce-test-wso2is-5.3.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.8.0-full-testgrid.yaml
> update ami id and region for job configs

- team-iam/shanika-wum-sce-test-wso2is-5.8.0rc3-full-testgrid.yaml
Add test config fro IS 5.8.0 
Update ami id and region
> update ami id region and add test config for IS 5.8.0

- RELEASES/intg-test-wso2is-master-testgrid-centos.yaml
- RELEASES/intg-test-wso2is-master-testgrid-rhel.yaml
- RELEASES/intg-test-wso2is-master-testgrid-ubuntu.yaml
- RELEASES/intg-test-wso2is-master-testgrid-windows.yaml
- RELEASES/intg-test-wso2is-master-testgrid.yaml
- RELEASES/sce-test-wso2is-testgrid.yaml
- wso2is-intg-testgrid-yaml
> update email list

- team-tg/wum-sce-test-helm-wso2ei.yaml
- team-tg/wum-sce-test-helm-wso2is.yaml
> Update jenkins job wum-sce-test-helm-wso2am
> Change deploymentConfig remoteRepository

- WUM/wum-sce-test-wso2is-5.8.0-full-testgrid.yaml
Update product scenario branch
> Change product scenario branch

- WUM/wum-sce-test-wso2is-5.8.0-full-testgrid.yaml
Update product scenario branch
> update product scenario branch

- team-iam/shanika-wum-sce-test-wso2is-5.8.0-full-testgrid.yaml
- team-iam/shanika-wum-sce-test-wso2is-5.8.0-master-full-testgrid.yaml
Update job configs for IS 5.8.0
> update job configs for IS 5.8.0

- team-ob/test-dev-sce-wso2ob-1.3.0-full-testgrid.yaml
> Add new job config yaml with ob configurations
> Add yaml file with ob configurations

- team-ob/wum-dev-sce-wso2ob-1.3.0-full-testgrid.yaml
> Change the url of the testgrid job config yaml
> Change the url of the testgrid job config yaml

- team-ob/test-dev-sce-wso2ob-1.3.0-full-testgrid.yaml
> Change the repository path in yaml
> Change the repository path

- team-ballerina/nats-connector.yaml
> Add ballerina nats-connector.yaml

- team-tg/wum-sce-test-helm-wso2am-2.6.0-full.yaml
> Change deployment and provisioner repository
NOTE:
```
``` …
> Change deployment and provisioner repository

- team-tg/wum-sce-test-helm-wso2is-5.8.0-full.yaml
This reverts commit e43d13fb41d2fb32b1c77bb5dcfababbe5366611.
NOTE:
```
``` …
> Revert "Change deployment repository"

- team-tg/janeth-perf-test-wso2am-2.6.0-test.yaml
> Change scenario config file name

- team-tg/wum-sce-test-helm-wso2ei-6.5.0-full.yaml
> Add resources for ActiveMQ and vfs. 
NOTE:
```
```
More details can be found in user guide - https://docs.google.com/document/d/1fYCUg97VsfoftEo1HfPWjdS6wh …
> Add integrator dependency resources

- WUM/wum-sce-test-wso2ei-6.5.0-full-testgrid.yaml
> Remove Suse linux from job config

- team-ob/test-dev-sce-wso2ob-1.3.0-full-testgrid.yaml
> updated the test lcoation

- team-ob/test-dev-sce-wso2ob-1.3.0-full-testgrid.yaml
> updated the aws-ob repo

- team-ob/test-dev-sce-wso2ob-1.3.0-full-testgrid.yaml
> added BrowserAutomation.HeadlessEnabled property

- team-ob/test-dev-sce-wso2ob-1.3.0-full-testgrid.yaml
> added InternalPrepareForTest property

- WUM/wum-sce-test-wso2is-5.8.0-full-testgrid.yaml
Update product scenarios running branch
> Change the Product scenarios running branch

- Ballerina-Integrator/s3-connector-test.yaml
> Add a new TG job for b7a integrator S3 connector.
> Add testgrid yaml for the S3 connector scenario tests

- team-tg/janeth-perf-test-wso2am-2.6.0-dis-jmeter-dep.yaml
- team-tg/janeth-perf-test-wso2am-2.6.0-test.yaml
> Add a new job config file for distributed Jmeter deployment
> Job config for distributed jmeter deployment

- team-tg/janeth-perf-test-wso2am-2.6.0-dis-jmeter-dep.yaml
> Add flag to control distributed jmeter deployment

- team-tg/wum-sce-test-helm-wso2am-2.6.0-new-charts.yaml
> Update exposedDeployents for wso2 api manager with analytics and cluster enabled. 
NOTE:
```
``` …
> Update exposed deployments list

- team-ballerina/database-tests.yaml
$Subject
NOTE:
```
```
More details can be found in user guide - https://docs.google.com/document/d/1fYCUg97VsfoftEo1HfPWjdS6whp4r0noGRzfaxsxmek/edit#
> Update dev branch

- team-tg/wum-sce-test-helm-wso2is-5.8.0-full.yaml
> Add test/set dependencies for wso2is; tomcat server
NOTE:
```
``` …
> Add tomcat server deployment

- team-ballerina/grpc-integration.yaml
$subject
NOTE:
```
```
More details can be found in user guide - https://docs.google.com/document/d/1fYCUg97VsfoftEo1HfPWjdS6whp4r0noGRzfaxsxmek/edit#
> Add new gRPC test scenario to DEV environment

- team-ballerina/http-resiliency.yaml
> Add http resiliency sample test 

- team-ballerina/client-handle-connection-errors.yaml
> Add http test config file for dev env

- Ballerina/http-resiliency.yaml
> $subject
NOTE:
```
```
More details can be found in user guide - https://docs.google.com/document/d/1fYCUg97VsfoftEo1HfPWjdS6whp4r0noGRzfaxsxmek/edit#
> Add http resiliency circuit breaker with retry test scenario

- team-tg/wum-sce-test-helm-wso2ei-6.5.0-full.yaml
> Add activemq and rabbitmq helm deployments to support scenario testing for enterprise integrator. 
NOTE 1:
NOTE 2:
``` …
```
> Add activemq and rabbitmq helm deployment

- team-tg/wum-sce-test-helm-wso2ei-6.5.0-full.yaml
> Add activemq/rabbitmq deployment scripts in HELM deploy phase.
NOTE 1:
NOTE 2:
``` …
```
> Add activemq/rabbitmq scripts for HELM deploy phase

- team-ballerina/grpc-integration.yaml
Change gRPC test job config in dev environment.
NOTE 1:
NOTE 2:
``` …
```
> Change grpc job config in dev environment

- team-tg/wum-sce-test-helm-wso2ei-6.5.0-full.yaml
> Add ei backend dependencies; vfs, acticvemq and rabbitmq
NOTE 1:
NOTE 2:
``` …
```
> Add vfs deployment and configurations

- team-ballerina/nats-tests.yaml
$Subject.
NOTE 1:
NOTE 2:
```
testgridYamlURL: https://raw.githubusercontent.com/ballerina-platform/ballerina-scenario-tes …
```
> Add NATS tests job

- team-ob/test-dev-sce-wso2ob-1.3.0-full-testgrid.yaml
> change aws repo

- Ballerina/grpc-unary-integration.yaml
> Add grpc testgrid job to production

- dev-tharindua-wso2am-intg-testgrid-full.yaml
- tharindua-wso2am-intg-testgrid-yaml
>add dev job for 3.0
NOTE 1:
NOTE 2:
```
testgridYamlURL: https://raw.githubusercontent.com/ballerina-platform/ballerina-s …
```
> add dev job for 3.0

- WUM/wum-sce-test-wso2is-5.9.0-full-testgrid.yaml
Add IS 5.9.0 TG job config to run scenario tests
Update email list in IS 5.7.0 job config
> Add IS 5.9.0 TG job config to run scenario tests

- team-tg/wum-sce-test-helm-wso2ei-6.5.0-full.yaml
> Add exposed deployments of ActiveMQ to check it's liveness
NOTE 1:
NOTE 2:
``` …
```
> Add exposed deployments

- team-tg/janeth-perf-wso2am-2.6.0.yaml
> Add a new job config yaml to do a wso2am performance test
> Add perf-test apim job config

- team-tg/janeth-perf-wso2am-2.6.0.yaml
> Fix the error in input parameters
> Fix input parameters error

- team-tg/janeth-perf-wso2am-2.6.0.yaml
> Add region parameter to the job config yaml.
> Add region

- team-tg/janeth-perf-wso2am-2.6.0.yaml
> Add remote branch for scenario config
> Add remote branch

- team-ob/test-dev-sce-wso2ob-1.3.0-full-testgrid.yaml
> updated aws-ob repo to support

- team-ob/test-dev-sce-wso2ob-1.3.0-full-testgrid.yaml
> updated testgrid job

- team-tg/janeth-perf-nested-apim-2.6.0.yaml
> Change input parameters

- team-ob/test-dev-sce-wso2ob-1.3.0-full-testgrid.yaml
- team-ob/test-dev-sce-wso2ob-1.4.0-full-testgrid.yaml
> updated ob testgridjobs

- team-ob/test-dev-sce-wso2ob-1.4.0-full-testgrid.yaml
> added region

- team-ob/test-dev-sce-wso2ob-1.4.0-full-testgrid.yaml
> changed aws repo

- team-tg/tg-log-extraction/rnm_helm_Injection.yaml
- team-tg/tg-log-extraction/rnm_helm_sidecar.yaml
- team-tg/tg-log-extraction/rnm_k8s_injection.yaml
- team-tg/tg-log-extraction/rnm_k8s_sidecar.yaml
Update the existing testgrid log extraction jobs for demo
> Update testgrid log extracion testgrid.yaml files

- team-tg/tg-log-extraction/rnm_helm_Injection.yaml
- team-tg/tg-log-extraction/rnm_helm_sidecar.yaml
> Fixed Param issues of injectionScript

- team-ob/test-dev-sce-wso2ob-1.4.0-full-testgrid.yaml
> changed the aws repo

- niluka_wso2is-wum-intg-testgrid-yaml 
Run integration test against product-is support
> Add new PR to TG

- wso2is-wum-intg-testgrid-yaml
> Point IS WUM integration tests to a new branch

- wso2is-wum-intg-testgrid-yaml
> Remove duplicate parameter

- WUM/wum-sce-test-wso2am-2.6.0-full-testgrid.yaml
Personal notification is no longer required since group is notified.
NOTE 1:
NOTE 2:
``` …
```
> Remove personal notifications

- wso2ei-openjdk11-intg-testgrid-yaml
> Test EI with openjdk11

- wso2ei-openjdk11-intg-testgrid-yaml
Change OS to Ubuntu18.
NOTE 1:
NOTE 2:
```
testgridYamlURL: https://raw.githubusercontent.com/ballerina-platform/ballerina …
```
> Change OS to Ubuntu18

- team-ob/test-dev-sce-wso2ob-1.4.0-full-testgrid.yaml
> adding wso2-enterprise/financial-open-banking

- team-ob/test-dev-sce-wso2ob-1.4.0-full-testgrid.yaml
> added amalka's fs repo

- wso2ei-openjdk11-intg-testgrid-yaml
_##_ Purpose
NOTE 1:
NOTE 2:
$> cat [testgrid-job-configs/Ballerina/bbg-kafka.yaml](https://github.com/wso2/testgrid-job-configs/blob/ce …
> Change OS to CentOS

- team-ob/test-dev-sce-wso2ob-1.4.0-full-testgrid.yaml
> updated test type

- team-ei/kasunA-intg-test-wso2ei-master-testgrid-660.yaml
This PR includes yaml file path for ei 660.
> Add yaml file for ei-660

- team-ballerina/bbg-data.yaml
> Change the yaml in dev env

- team-ei/kasunA-intg-test-wso2-Micro-Integrator-master-testgrid.yaml
> This PR includes yaml file path for the Micro Integrator.
> Add yaml file for the MI

- WUM/wum-sce-test-wso2is-5.9.0-full-testgrid.yaml
> Adding openjdk 11 support for TG job config

- team-iam/vim-wum-sce-test-wso2is-5.9.0-full-testgrid.yaml
> Test IS 5.9.0 JDK11 Scenarios

- team-iam/openjdk11-wum-sce-test-wso2is-5.9.0-full-testgrid.yaml
Add Openjdk 11 with IS 5.9.0 to TG Dev env
> Add jobconfig to run scenario tests against openjdk11

- team-ballerina/bbg-data-test.yaml
- team-ballerina/bbg-data.yaml
> Rename the bbg-data yaml

- team-ballerina/bbg-data-test.yaml
> Change the bbg-data-test yaml

- team-ballerina/bbg-data-test.yaml
> Change the branch

- team-ballerina/bbg-data-test.yaml
> Change the yaml file to point master

- team-ballerina/bbg-data-test.yaml
Reverts wso2/testgrid-job-configs#409
> Revert "Change the yaml file to point master"

- Ballerina/bbg-kafka.yaml
- Ballerina/kafka.yaml
> Added new job: __`kafka`__
> Removed job: __`bbg-kafka`__
NOTE 1:
NOTE 2:
``` …
```
> Update ballerina Kafka job config

- team-ob/test-dev-sce-wso2ob-1.4.0-full-testgrid.yaml
> updated tesgrid yaml pointing correct locations

- team-ob/test-dev-sce-wso2ob-1.4.0-full-testgrid.yaml
> added fs-group

- WUM/wum-sce-test-wso2ei-6.5.0-full-testgrid.yaml
Change the AWS regions of jobs
NOTE 1:
NOTE 2:
``` …
```
> Allow the jobs run in different regions

- WUM/wum-sce-test-wso2is-5.9.0-full-testgrid.yaml
> Add oracle 11 db support

- dev-niron-wso2am-intg-testgrid-full.yaml
> Adding a testgrid yaml with Windows scenario. The yaml is pointing to an external testgrid yaml configuration.
> Adding new yaml with Windows scenario

- team-ballerina/bbg-database-test.yaml
> Add yaml file to test the database

- team-ballerina/bbg-database-test.yaml
> Change the url in the yaml file

- dev-niron-wso2am-intg-rhel-testgrid-full.yaml
> add rhel testgrid configs for apim

- WUM/wum-sce-test-wso2ob-1.4.0-full-testgrid.yaml
> Added OB 1.4.0 yaml
NOTE 1:
NOTE 2:
```
testgridYamlURL: https://raw.githubusercontent.com/ballerina-platform/ballerina- …
```
> OB 1.4.0 Testgrid-job-config yaml

- WUM/wum-sce-test-wso2ei-6.5.0-full-testgrid.yaml
Change EI 6.5.0 job configs
NOTE 1:
NOTE 2:
``` …
```
> Fix EI log publish issue

- WUM/wum-sce-test-wso2ei-6.3.0-full-testgrid.yaml
Fix log publish issue for EI 630
NOTE 1:
NOTE 2:
``` …
```
> Fix log publish issue for EI 630

- WUM/wum-sce-test-wso2ei-6.1.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.1.1-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.2.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.4.0-full-testgrid.yaml
> Remove Elasticsearch endpoint from EI builds

- WUM/wum-sce-test-wso2ei-6.1.1-full-testgrid.yaml
> Change AWS region for EI  6.1.1 job

- WUM/wum-sce-test-wso2ei-6.1.1-full-testgrid.yaml
Resource limitation exceeded
```
Status: CREATE_FAILED, Resource Type: AWS::EC2::EIP, Logical ID: WSO2EIEIP, Status Reason: The maximum number of addresses has been reached. (Service: AmazonEC2; Status Code: 400; Error Code: AddressLimitExceeded; Request ID: 83d21545-03a3-47f4-8785-410e9b285db9)
```
NOTE 1:
NOTE 2:
You can point to an external testgrid yaml by having the job …
> Change EI 611 build region to us-west-1

- WUM/wum-sce-test-wso2am-2.6.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.2.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2esb-4.9.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2esb-5.0.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.2.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.3.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.8.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.9.0-full-testgrid.yaml
Add the proper email groups to the WUM builds
NOTE 1:
NOTE 2:
``` …
```
> Add email groups to the WUM builds

- WUM/wum-sce-test-wso2ei-6.6.0-full-testgrid.yaml
Add EI 6.6.0 job
NOTE 1:
NOTE 2:
```
testgridYamlURL: https://raw.githubusercontent.com/ballerina-platform/ballerina-scena …
```
> Add EI 6.6.0 job

- WUM/wum-sce-test-wso2is-5.9.0-full-testgrid.yaml
Update email list
NOTE 1:
NOTE 2:
```
testgridYamlURL: https://raw.githubusercontent.com/ballerina-platform/ballerina-scen …
```
> Update email address in yaml

- WUM/wum-sce-test-wso2ob-1.3.0-full-testgrid.yaml
> Added a new job pointing OB 1.3.0 deployment.
NOTE 1:
NOTE 2:
``` …
```
> Add OB 1.3.0 Testgrid-job-config yaml

- WUM/wum-sce-test-wso2ei-6.6.0-full-testgrid.yaml
Reverts wso2/testgrid-job-configs#440
> Revert "Change EI660 scenario test location to wso2-support"

- WUM/wum-sce-test-wso2is-5.10.0-full-testgrid.yaml
Run scenario tests for wso2is-5.10.0 on the WSO2 Testgrid.
NOTE 1:
NOTE 2:
``` …
```
> Add IS 5.10.0 job

- WUM/wum-sce-test-wso2is-5.10.0-full-testgrid.yaml
Run tests for IS 5.10.0 on TG.
NOTE 1:
NOTE 2:
``` …
```
> Update the JDK11 parameter

- WUM/wum-sce-test-wso2is-5.10.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.2.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.3.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.8.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.9.0-full-testgrid.yaml
Send TestGrid build mails to TestGrid devs. (They belong to the integration BU)
NOTE 1:
NOTE 2:
``` …
```
> Add integration-builder@wso2.com to all the IS builds

- WUM/wum-sce-test-wso2ei-6.6.0-full-testgrid.yaml
Add ADOPT_OPEN_JDK11 to EI660 job
NOTE 1:
NOTE 2:
``` …
```
> Add ADOPT_OPEN_JDK11 to EI660 job

- WUM/wum-sce-test-wso2is-5.9.0-full-testgrid.yaml
Update the JDK11 parameter from OPEN_JDK11 to ADOPT_OPEN_JDK11
NOTE 1:
NOTE 2:
``` …
```
> Change JDK11 parameter value

- WUM/wum-sce-test-wso2ei-6.4.0-full-testgrid.yaml
>  Add Oracle-SE2-19.0 to the wum-sce-test-wso2ei-6.4.0-full-testgrid.yaml.
> Add DB Oracle-SE2-19.0

- WUM/wum-sce-test-wso2ob-1.5.0-full-testgrid.yaml
Run tests for OB 1.5.0 on TestGrid
NOTE 1:
NOTE 2:
``` …
```
> Add OB 1.5.0 job

- WUM/wum-sce-test-wso2ei-6.6.0-full-testgrid.yaml
> Add Oracle-SE2-19.0 to the wum-sce-test-wso2ei-6.6.0-full-testgrid.yaml.
> Add Oracle-SE2-19.0

- WUM/wum-sce-test-wso2is-5.9.0-full-testgrid.yaml
Introduce at_least_one algorithm as a jobConfig parameter to the TG yaml.
NOTE 1:
NOTE 2:
``` …
```
> Introduce at_least_one algorithm

- WUM/wum-sce-test-wso2is-5.9.0-full-testgrid.yaml
Reverts wso2/testgrid-job-configs#451
> Revert "Introduce at_least_one algorithm"

- WUM/wum-sce-test-wso2am-3.0.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2am-3.1.0-full-testgrid.yaml
Add APIM 3.1.0 and 3.0.0 jobs
NOTE 1:
NOTE 2:
``` …
```
> Add APIM 3.1.0 and 3.0.0 jobs

- WUM/wum-sce-test-wso2am-3.0.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2am-3.1.0-full-testgrid.yaml
Change scenario test location for APIM 3.0.0 and 3.1.0
NOTE 1:
NOTE 2:
``` …
```
> Change scenario test location for APIM 3.0.0 and 3.1.0

- WUM/wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
Add Oracle DB to IS 5.7.0
NOTE 1:
NOTE 2:
``` …
```
> Add Oracle DB to IS 5.7.0

- WUM/wum-sce-test-wso2am-2.6.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2am-3.0.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2am-3.1.0-full-testgrid.yaml
Remove apim-group@wso2.com as it is no longer available.
NOTE 1:
NOTE 2:
``` …
```
> Remove apim-group@wso2.com

- WUM/wum-sce-test-wso2mi-1.2.0-full-testgrid.yaml
> Add micro-integrator job for 1.2.0
NOTE 1:
NOTE 2:
``` …
```
> Add micro-integrator 1.2.0 job

- WUM/wum-sce-test-wso2mi-1.2.0-full-testgrid.yaml
Add integration-builder@wso2.com to the MI job.
NOTE 1:
NOTE 2:
``` …
```
> Add integration-builder@wso2.com to the MI job

- WUM/wum-sce-test-wso2mi-1.2.0-full-testgrid.yaml
> Update scenario repository
NOTE 1:
NOTE 2:
``` …
```
> Update scenario repository

- WUM/wum-sce-test-wso2is-5.6.0-full-testgrid.yaml
Add IS 5.6.0 Jenkins build.
NOTE 1:
NOTE 2:
``` …
```
> Add IS 5.6.0 build

- WUM/wum-sce-test-wso2ei-6.1.1-full-testgrid.yaml
Move EI611 job to us-east-1
```
The maximum number of addresses has been reached. (Service: AmazonEC2; Status Code: 400; Error Code: AddressLimitExceeded; Request ID: 7ae7d673-0db1-49ae-b630-bc012b4ea5e8)
```
NOTE 1:
NOTE 2:
$> cat [testgrid-job-configs/Ballerina/bbg-kafka.yaml](https://github …
> Move EI611 job to us-east-1

- WUM/wum-sce-test-wso2is-5.6.0-full-testgrid.yaml
> Pointing to scenario test support repository.
NOTE 1:
NOTE 2:
``` …
```
> Update IS 5.6.0 build configs

- WUM/wum-sce-test-wso2is-5.6.0-full-testgrid.yaml
Fix URL issue in 560 yaml
NOTE 1:
NOTE 2:
``` …
```
> Fix URL issue in 560 yaml

- WUM/wum-sce-test-wso2am-3.2.0-full-testgrid.yaml
Add APIM 3.2.0 scenario test job
NOTE 1:
NOTE 2:
``` …
```
> Add APIM 3.2.0 scenario test job

- Integration-Test/wso2am-2.1.0-intg-testgrid.yaml
- wso2am-2.1.0-intg-testgrid.yaml
> Add Integration Test Yaml
NOTE 1:
NOTE 2:
``` …
```
> Add Testgrid job for Integration Tests

- WUM/wum-sce-test-wso2am-3.2.0-full-testgrid.yaml
Moving the job to run with the master branch of aws-apim repository
NOTE 1:
NOTE 2:
``` …
```
> Modify api-m 3.2.0 job to run with snapshot

- WUM/wum-sce-test-wso2ei-6.5.0-full-testgrid.yaml
Move EI650 job to us-east-1 tentatively.
NOTE 1:
NOTE 2:
``` …
```
> Move EI650 job to us-east-1

- WUM/wum-sce-test-wso2ob-1.3.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ob-1.4.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ob-1.5.0-full-testgrid.yaml
> Added new parameter for OB specific Testgrid-job-config yaml files.
NOTE 1:
NOTE 2:
``` …
```
> Update OB Testgrid-job-config yaml files

- Integration-Test/master-branch-releases/intg-test-wso2am-testgrid.yaml
- Integration-Test/master-branch-releases/intg-test-wso2mi-testgrid.yaml
- Integration-Test/wso2am-2.1.0-intg-testgrid.yaml
- Integration-Test/wum-intg-test-wso2mi-1.1.0-testgrid.yaml
> Add Integration APIM test

- WUM/wum-sce-test-wso2am-3.2.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2am-latest-jenkins-build-full-testgrid.yaml
Add new job for Jenkins latest build for APIM
NOTE 1:
NOTE 2:
``` …
```
>  Add new job for Jenkins latest build for APIM

- testgrid-centralized-puppetserver.yaml
Add job for centralized-puppet server POC
NOTE 1:
NOTE 2:
``` …
```
> Add job for centralized-puppetserver POC

- testgrid-centralized-puppetserver.yaml
> Change region to us-east-1

- Integration-Test/wso2is-5.10.0-intg-testgrid.yaml
> Add IS 5.10.0 integration testgrid yaml

- WUM/wum-sce-test-wso2am-2.6.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2am-3.0.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2am-3.1.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2am-3.2.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2am-latest-jenkins-build-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.1.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.1.1-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.2.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.3.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.4.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.5.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ei-6.6.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2esb-4.9.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2esb-5.0.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.10.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.2.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.3.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.6.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.8.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.9.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2mi-1.2.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ob-1.3.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ob-1.4.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ob-1.5.0-full-testgrid.yaml
Send mails for each build to the new TG owners
NOTE 1:
NOTE 2:
``` …
```
> Configure APIM builds with new TG owner emails

- WUM/wum-sce-test-wso2am-3.0.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2am-3.1.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2am-3.2.0-full-testgrid.yaml
Fix email formatting for APIM
NOTE 1:
NOTE 2:
``` …
```
> Fix email formatting for APIM

- WUM/wum-sce-test-wso2is-latest-jenkins-build-testgrid.yaml
> Add job config for latest jenkins build testgrid for IS-5.11 Snapshot
NOTE 1:
NOTE 2:
``` …
```
> Add job config for latest jenkins build testgrid

- WUM/wum-sce-test-wso2is-latest-jenkins-build-testgrid.yaml
> yaml file pointed to apim/ path and also fix the mail list
> Fix issue in yaml file path

- Integration-Test/wum-intg-test-wso2mi-1.2.0-testgrid.yaml
$subject
NOTE 1:
NOTE 2:
$> cat [testgrid-job-configs/Ballerina/bbg-kafka.yaml](https://github.com/wso2/testgrid-job-configs/blob/ce9184 …
> Add testgrid script for mi 1.2.0

- WUM/wum-sce-test-wso2is-latest-jenkins-build-testgrid.yaml
> Add IS samples cloud-formation script
> Add IS samples cloud-formation script

- WUM/wum-sce-test-wso2ob-1.5.0-full-testgrid.yaml
> Update branch to OB-2.0.0 to run tests

- wso2is-intg-testgrid-yaml
This PR includes the changes to update the mail list and update the infrastructure values to run the integration tests.
> Update mail list and change infrastructure values

- Integration-Test/wum-intg-test-wso2esb-5.0.0-testgrid.yaml
> Add testgrid script for esb 5.0.0

- Integration-Test/wum-intg-test-wso2esb-5.0.0-testgrid.yaml
> Update testgrid.yaml for esb-5.0.0

- Integration-Test/wum-intg-test-wso2ei-6.6.0-testgrid.yaml
This PR adds configuration to onboard EI-6.6.0 integration tests and update MI-1.2.0 config to include ORACLE_JDK11, Ubuntu-16.04
NOTE 1:
NOTE 2:
$> cat [testgrid-job-configs/Ballerina/bbg-kafka.yaml](https://github.com/wso2/testgrid-job-configs/blob/ce9184d7e1c3719d74ad56325239f54bff21e18b/Ba …
> Onboard EI-6.6.0 integration tests

- Integration-Test/wum-intg-test-wso2ei-6.6.0-testgrid.yaml
> Update testgrid.yaml for ei-6.6.0

- Integration-Test/wum-intg-test-wso2mi-1.2.0-testgrid.yaml
> Update instance type in mi-1.2.0 yaml

- Integration-Test/wum-intg-test-wso2ei-6.6.0-testgrid.yaml
> Update git branch for EI-6.6.0

- Integration-Test/master-branch-releases/intg-test-wso2am-testgrid.yaml
> Adding changes for APIM 4.0.0

- Integration-Test/master-branch-releases/intg-test-wso2am-testgrid.yaml
> Adding instance type parameter
> Adding instance type parameter

- WUM/wum-sce-test-wso2ob-1.5.0-full-testgrid.yaml
> Update the emailToList in wso2ob-1.5.0
NOTE 1:
NOTE 2:
``` …
```
> Update the emailToList in wso2ob-1.5.0

- WUM/wum-sce-test-wso2is-5.2.0-full-testgrid.yaml
Fix the version error in IS520
NOTE 1:
NOTE 2:
``` …
```
> Fix the version error in IS520

- Integration-Test/master-branch-releases/intg-test-wso2am-testgrid.yaml
- WUM/wum-sce-test-wso2am-latest-jenkins-build-testgrid.yaml
> Changing version to 4.0.0

- WUM/wum-sce-test-wso2is-5.6.0-full-testgrid.yaml
Change the certificate to wso2_testgrid as the previous one is expired.
NOTE 1:
NOTE 2:
``` …
```
> Change the certificate to wso2_testgrid

- WUM/wum-sce-test-wso2is-5.8.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.9.0-full-testgrid.yaml
> Change the cert to wso2_testgrid for 580 and 590

- WUM/wum-sce-test-wso2am-3.0.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2am-3.1.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.7.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-latest-jenkins-build-testgrid.yaml
> Update the LB cert

- Updates-2.0/u2-sce-test-wso2ei-6.5.0-full-testgrid.yaml
Add updates 2.0 testgrid job for wso2ei-6.5.0
> Add updates 2.0 testgrid job for wso2ei-6.5.0

- Updates-2.0/u2-sce-test-wso2ei-6.6.0-full-testgrid.yaml
Add updates 2.0 testgrid job for wso2ei-6.6.0
> Add updates 2.0 testgrid job for wso2ei-6.6.0

- Integration-Test/master-branch-releases/intg-test-wso2am-testgrid.yaml
> Adding Sql Server 15

- Updates-2.0/u2-sce-test-wso2ei-6.1.0-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2ei-6.1.1-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2ei-6.2.0-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2ei-6.3.0-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2ei-6.4.0-full-testgrid.yaml
Add testgrid pipeline for updates 2.0 EI
> Add testgrid pipeline for updates 2.0 EI

- Updates-2.0/u2-sce-test-wso2ob-2.0.0-full-testgrid.yaml
Add updates 2.0 testgrid job for wso2ob-2.0.0
> Add updates 2.0 testgrid job for wso2ob-2.0.0

- Updates-2.0/u2-sce-test-wso2is-5.10.0-full-testgrid.yaml
Add wso2is-5.10.0 job for u2 testgrid
> Add wso2is-5.10.0 job for u2 testgrid

- Updates-2.0/u2-sce-test-wso2is-5.2.0-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2is-5.3.0-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2is-5.6.0-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2is-5.7.0-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2is-5.8.0-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2is-5.9.0-full-testgrid.yaml
Add updates 2.0 testgrid job for wso2is
> Add updates 2.0 testgrid job for wso2is

- Integration-Test/master-branch-releases/intg-test-wso2am-testgrid.yaml
Changing the pack to last build
> Changing the pack to last build

- last-successful-build/sce-test-wso2mi-4.0.0-snapshot-testgrid.yaml
Create TestGrid job config for MI-4.0.0 last successful build
NOTE 1:
> Create TestGrid job config for MI-4.0.0 last successful build

- Integration-Test/master-branch-releases/intg-test-wso2mi-testgrid.yaml
> Upgrade to 4.0.0 snapshot

- Integration-Test/master-branch-releases/intg-test-wso2mi-testgrid.yaml
> Update the TEST_SCRIPT_URL for MI400

- Integration-Test/master-branch-releases/intg-test-wso2mi-testgrid.yaml
> Change the TEST_SCRIPT_URL for MI400

- Updates-2.0/u2-sce-test-wso2esb-4.9.0-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2esb-5.0.0-full-testgrid.yaml
> Add U2 wso2esb job configs

- Integration-Test/master-branch-releases/intg-test-wso2am-testgrid.yaml
> Updating the pack to RC

- Integration-Test/master-branch-releases/intg-test-wso2am-testgrid.yaml
Reverts wso2/testgrid-job-configs#523
> Revert "Updating the pack to RC"

- Updates-2.0/u2-sce-test-wso2am-2.6.0-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2am-3.2.0-full-testgrid.yaml
> Add APIM u2 jobs

- Updates-2.0/u2-sce-test-wso2ob-2.0.0-full-testgrid.yaml
> Update 2.0.0 api version

- Updates-2.0/u2-sce-test-wso2ob-1.5.0-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2ob-2.0.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2ob-1.5.0-full-testgrid.yaml
> Update job configs

- Staging-Updates-2.0/u2-sce-test-wso2ob-1.5.0-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2ob-1.5.0-full-testgrid.yaml
> Add job configuration for U2 UAT and staging

- Updates-2.0/u2-sce-test-wso2ob-2.0.0-full-testgrid.yaml
> [OB] [2.0.0] Update certificate name

- Updates-2.0/u2-sce-test-wso2ob-1.5.0-full-testgrid.yaml
> [OB] Update api version to 3.1.5 for UK 1.5.0 U2 staging build

- Staging-Updates-2.0/u2-sce-test-wso2ob-1.5.0-staging-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2ob-1.5.0-full-testgrid.yaml
> [OB] Update api version to 3.1.5 for UK 1.5.0 U2 staging build issue fixed

- WUM/wum-sce-test-wso2am-3.2.0-full-testgrid.yaml
Adding changes to support latest postgres versions
> Adding changes to support latest postgres versions

- Updates-2.0/u2-sce-test-wso2am-2.6.0-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2am-3.2.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2am-2.6.0-full-testgrid.yaml
Adding support for postgres latest versions
> Adding support for postgres latest versions

- Updates-2.0/u2-sce-test-wso2am-4.0.0-full-testgrid.yaml
> Adding u2 sce for apim 4.0.0

- Updates-2.0/u2-sce-test-wso2is-5.10.0-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2is-5.2.0-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2is-5.3.0-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2is-5.6.0-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2is-5.8.0-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2is-5.9.0-full-testgrid.yaml
> Change to U2 product branch

- UI-Testing/u2-ui-integration-test-wso2am-3.2.0-staging-testgrid.yaml
Reverts wso2/testgrid-job-configs#543
> Revert "Added report generation method as CYPRESS."

- Updates-2.0/u2-intg-test-wso2am-3.2.0-full-testgrid.yaml
> update2.0 integration test testgrid for 3.2.0

- Updates-2.0/u2-intg-test-wso2am-4.0.0-full-testgrid.yaml
Add Integration test test grid build for 4.0.0
Add integration test grid for 4.0.0
NOTE 1:
NOTE 2:
``` …
```
> Add Integration test testgrid build for 4.0.0

- Updates-2.0/u2-intg-test-wso2am-3.2.0-full-testgrid.yaml
- Updates-2.0/u2-intg-test-wso2am-4.0.0-full-testgrid.yaml
> add fixes to build 4.0.0

- Updates-2.0/u2-intg-test-wso2am-3.2.0-full-testgrid.yaml
- Updates-2.0/u2-intg-test-wso2am-4.0.0-full-testgrid.yaml
> add DBName input parameter

- Updates-2.0/u2-sce-test-wso2is-5.11.0-full-testgrid.yaml
Add wso2is-5.11.0 job for u2 testgrid.
NOTE 1:
NOTE 2:
``` …
```
> Add wso2is-5.11.0 job for u2 testgrid

- WUM/wum-sce-test-wso2is-5.3.0-full-testgrid.yaml
Change the Postgres to the 10.19.
- Associated PR: https://github.com/wso2-support/aws-is/pull/261
> Change the postgres to the 10.19

- Updates-2.0/u2-sce-test-wso2is-5.10.0-full-testgrid.yaml
- Updates-2.0/u2-sce-test-wso2is-5.11.0-full-testgrid.yaml
- WUM/wum-sce-test-wso2is-5.10.0-full-testgrid.yaml
Bump the Postgres to non deprecated version.
> Change the Postgres to the 12.9

- Updates-2.0/u2-intg-test-wso2am-3.2.0-full-testgrid.yaml
- Updates-2.0/u2-intg-test-wso2am-4.0.0-full-testgrid.yaml
change Postgres-10.5 to Postgres-10.19
> change Postgres-10.5 to Postgres-10.19

- UI-Testing/u2-ui-integration-test-wso2am-4.1.0-staging-testgrid.yaml
> Add new Jenkins job for APIM 4.1.0 UI integration tests
NOTE 1:
NOTE 2:
``` …
```
> Add pipeline for APIM 4.1.0 UI integration tests

- Updates-2.0/u2-sce-test-wso2am-4.1.0-full-testgrid.yaml
> Added 4.1.0 U2 jenkins job.

- Updates-2.0/u2-sce-test-wso2is-5.6.0-full-testgrid.yaml
> Remove postgress 10.11

- Updates-2.0/u2-intg-test-wso2am-4.1.0-full-testgrid.yaml
> Change the ALB certificate

- Updates-2.0/u2-intg-test-wso2am-4.1.0-full-testgrid.yaml
Reverts wso2/testgrid-job-configs#575
> Revert "Update u2-intg-test-wso2am-4.1.0-full-testgrid.yaml"

- Updates-2.0/u2-intg-test-wso2am-4.1.0-full-testgrid.yaml
Reverts wso2/testgrid-job-configs#574
> Revert "Change the ALB certificate"

- UI-Testing/u2-ui-integration-test-wso2am-4.1.0-staging-testgrid.yaml
> Update infra provisioning location

- Updates-2.0/u2-intg-test-wso2am-4.1.0-full-testgrid.yaml
> update build to c4.2x.large

- UI-Testing/u2-ui-integration-test-wso2am-4.1.0-staging-testgrid.yaml
> Update remoteRepository format

- RELEASES/intg-test-wso2is-master-testgrid.yaml
>  This PR updates the DB and  the location.
> add db and location

- RELEASES/intg-test-wso2is-master-testgrid.yaml
> This PR updates instance type and updates the JDK type as well
> Update instance type

- RELEASES/intg-test-wso2is-master-testgrid.yaml
> This PR updates the github urls
> Update github url

- Updates-2.0/u2-intg-test-wso2am-3.2.0-full-testgrid.yaml
- Updates-2.0/u2-intg-test-wso2am-4.0.0-full-testgrid.yaml
- Updates-2.0/u2-intg-test-wso2am-4.1.0-full-testgrid.yaml
> update db type

- WUM/wum-sce-test-wso2ei-6.6.0-full-testgrid.yaml
> Change region of WUM EI 6.6.0 build

- WUM/wum-sce-test-wso2is-5.10.0-full-testgrid.yaml
> To test the changes with the test script for simplified testgrid  affects the existing testgrid
> Change the test repo in testgrid pipeline configs 5.10.0 WUM 

- WUM/wum-sce-test-wso2is-5.10.0-full-testgrid.yaml
>To test the changes with the test script for simplified testgrid affects the existing testgrid
> Change the test branch in testgrid pipeline configs 5.10.0 WUM

- WUM/wum-sce-test-wso2is-5.10.0-full-testgrid.yaml
Reverts wso2/testgrid-job-configs#589
> Revert "Change the test repo in testgrid pipeline configs 5.10.0 WUM "
