wso2/testgrid-job-configs

infra-test/wum-sce-test-wso2ei-6.2.0-full-testgrid.yaml
infra-test/wum-sce-test-wso2ei-6.3.0-full-testgrid.yaml

> Run tests without Oracle 11 database version.
> Remove Oracle 11 database version from tets.
> Comment the Oracle 11 database version from cloud formation template.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
- Integration tests
> N/A
> N/A
> N/A
> N/A
> JDK Version : 8 , OS : Ubuntu 18/CentOS7, PostgreSQL 9.6/10.5, MSSQL 13.00/14.00, Oracle 12.1
> N/A

Comment Oracle 11 database version for EI-620 and EI-630

---

infra-test/wum-sce-test-wso2am-2.1.0-full-testgrid.yaml
infra-test/wum-sce-test-wso2am-2.2.0-full-testgrid.yaml
infra-test/wum-sce-test-wso2am-2.5.0-full-testgrid.yaml
infra-test/wum-sce-test-wso2am-2.6.0-full-postgres-testgrid.yaml
infra-test/wum-sce-test-wso2am-2.6.0-full-testgrid.yaml
wum-dev-sce-devtest-wso2am-2.6.0-full-testgrid.yaml

APIM test cases expect ProductVersion property in deployment.properties file to identify the running deployment version. This property is then used to select the specific test suite that needs to run.

Add ProductVersion input param

---

WUM/wum-sce-test-wso2am-2.1.0-full-testgrid.yaml
WUM/wum-sce-test-wso2am-2.6.0-full-testgrid.yaml

Add RemoteProductDir input parameter for apim 2.6.0 and 2.1.0

---

wum-dev-sce-devtest-wso2am-2.6.0-full-testgrid.yaml

Add RemoteProductDir input parameter for apim 2.6.0

---

team-apim/tanya-corretto-wso2am-2.6.0-full.yaml

There was no test grid job with Corretto JDK for apim distributed deployment.
This PR adds the apim corretto test grid job.
Inserted a new file called "tanya-corretto-wso2am-2.6.0-full.yaml" under "team-apim"

Add apim corretto test grid job for 2.6.0

---

team-apim/tanya-corretto-wso2am-2.6.0-full.yaml

CentOS was missing in the Infrastructure combination of corretto test config. This PR adds that.
Running scenario tests for CentOS, Corretto JDK and MySQL combination.
Added CentOS to the infrastructure config.

 Add centOs to apim 2.6 corretto test config

---

infra-test/wum-sce-test-wso2am-2.6.0-full-testgrid-SUSE.yaml

> Add new configurations for SUSE Linux tests.
> Use different repository and other configurations for APIM2.6.0 test with SUSE Linux.

Update configurations for SUSE-Linux tests in APIM 2.6.0

---

team-tg/kosala-tg-cost-optimization-tester.yaml

> Change JDK resource type due to database doe not contain the previously given name.
> Change the Open JDK 8 infrastructure name from the yaml configuration file.

Change JDK resource name

---

team-tg/kosala-tg-cost-optimization-tester.yaml

> Add wso2 is test configurations to test schedule build  generation.
> Add wso2 is test configurations and test parameters to build test plans with new scheduled build generator.

Update yaml configuration file

---

team-ei/dev_mi_docker.yaml

This yaml file contains the configurations to run the Micro integrator tests in a docker container. 
##Task
https://github.com/wso2/micro-integrator/issues/169

Adding Micro integrator docker yaml file

---

team-tg/rnm-k8s.yaml

New K8S job for testing log file sidecar
NOTE:
```
``` …

new k8s job

---

team-tg/wum-sce-test-helm-wso2am-2.6.0-new-charts.yaml

> Correct erroneous syntax in job configuration yaml.
NOTE:
```
``` …

Correct syntax for exposedDeployments

---

wso2is-wum-intg-testgrid-yaml

Enable test mode WUM for IS integration tests.
NOTE 1:
NOTE 2:
``` …
```

Add job for IS integration tests with test mode WUM

---

WUM/wum-sce-test-wso2ei-6.1.0-full-testgrid.yaml
WUM/wum-sce-test-wso2ei-6.1.1-full-testgrid.yaml
WUM/wum-sce-test-wso2ei-6.2.0-full-testgrid.yaml
WUM/wum-sce-test-wso2ei-6.3.0-full-testgrid.yaml
WUM/wum-sce-test-wso2ei-6.4.0-full-testgrid.yaml
WUM/wum-sce-test-wso2ei-6.5.0-full-testgrid.yaml
WUM/wum-sce-test-wso2esb-4.9.0-full-testgrid.yaml
WUM/wum-sce-test-wso2esb-5.0.0-full-testgrid.yaml

Currently testgrid job mails are sent only to selected people. Hence, adding the newly created mailing list to the config so the people in the operations team can monitor the builds.
NOTE 1:
NOTE 2:
$> cat [testgrid-job-configs/Ballerina/bbg-kafka.yaml](https://github.com/wso2/testgrid-job-con …

Add integration-builder mailing list to integration jobs

---

WUM/wum-sce-test-wso2is-5.7.0-full-testgrid.yaml

There is an infra error when deploying servers in **Oracle-SE2-12.1** environment. This PR removes that environment from the testgrid. This PR should be reverted once that issue is fixed.
NOTE 1:
NOTE 2:
$> cat [testgrid-job-configs/Ballerina/bbg-kafka.yaml](https://github.com/wso2/testgrid-jo …

Remove Oracle environment temporarily

---

team-tg/janeth-perf-apim-2.6.0-two-jmeter-servers.yaml

> Add a new job for apim-2.6.0 pattern-1 performance testing with two JMeter servers.

Add new job for perf-apim-2.6.0

---

WUM/wum-sce-test-wso2ei-6.6.0-full-testgrid.yaml

Change RemoteProductDir of EI 6.6.0 job.
NOTE 1:
NOTE 2:
``` …
```

Change RemoteProductDir of EI 6.6.0 job

---

WUM/wum-sce-test-wso2ei-6.6.0-full-testgrid.yaml

Run EI 6.6.0 jobs on Testgrid
NOTE 1:
NOTE 2:
``` …
```

Change EI660 scenario test location to wso2-support

---

Ballerina/artemis-connector-scenario-tests.yaml

> Remove testgrid job for artemis connector as it is no more in the ballerina distribution
NOTE 1:
NOTE 2:
``` …
```

Remove testgrid job for artemis connector

---

WUM/wum-sce-test-wso2is-latest-jenkins-build-testgrid.yaml

Config MariaDB in infrastructure Config to run the scenario tests with MariaDB + MariaDB Driver for IS 5.11.0
wso2/product-is#10264

Config MariaDB as a infrastructure value

---

WUM/wum-sce-test-wso2is-latest-jenkins-build-testgrid.yaml

Update the scenario test job config to test the compatibility with SI 5.11.0 for MySQL 8 DB version.
https://github.com/wso2/product-is/issues/9781

Add MySQL 8 as a DB version for IS 5.11.0

---

WUM/wum-sce-test-wso2is-5.10.0-full-testgrid.yaml

There is a customer request for  IS 5.10 compatibility with Postgres-12.3. This PR includes the change for the job config in order to run the 5.10 scenario tests.

Add Postgres-12.3 as a infrastructure value to test compatibility with IS 5.10

---

Integration-Test/wum-intg-test-wso2ei-6.6.0-testgrid.yaml

Reverts wso2/testgrid-job-configs#498
This PR reverts the product-git branch to support-6.6.0

Revert "Update git branch for EI-6.6.0"

---

Staging-Updates-2.0/u2-sce-test-wso2ob-1.5.0-staging-testgrid.yaml
Staging-Updates-2.0/u2-sce-test-wso2ob-2.0.0-staging-testgrid.yaml
Updates-2.0/u2-sce-test-wso2ob-1.5.0-full-testgrid.yaml
Updates-2.0/u2-sce-test-wso2ob-2.0.0-full-testgrid.yaml
WUM/wum-sce-test-wso2ob-1.3.0-full-testgrid.yaml
WUM/wum-sce-test-wso2ob-1.4.0-full-testgrid.yaml
WUM/wum-sce-test-wso2ob-1.5.0-full-testgrid.yaml

> This PR will add BrowserAutomation.BrowserPreference to OB inputParameteres. The purpose is to run either Firefox or Chrome browser for test automation depending on the user preference. The default value is set to firefox
NOTE 1:
NOTE 2:
$> cat …

[OB][Test-Grid] Add BrowserAutomation.BrowserPreference to OB inputParameters
